### ISSUE TITLE
Vagrant 1.3.3 incompatability?

### ISSUE THREAD

**Issue by erunion** [joshmcarthur/vagrant-list#7]
Upgraded to from Vagrant 1.2.7 to 1.3.3 and I am now getting this error:

<pre>ALL:
dyld: Symbol not found: _iconv
  Referenced from: /usr/lib/libcups.2.dylib
  Expected in: /Applications/Vagrant/bin/../embedded/lib/libiconv.dylib
 in /usr/lib/libcups.2.dylib
translation missing: en.vagrant.errors.VBoxManage list returned non-zero status</pre>

**Comment by joshmcarthur** [comment]
Hi @jonursenbach - thanks for reporting this issue.

I'm getting the same issue after updating to 1.3.3, but it does seem to be an issue with vagrant itself, rather than this specific plugin:
1. https://github.com/mitchellh/vagrant/issues/2231
2. https://github.com/mitchellh/vagrant/issues/2219

Since there has been activity on these issues both in the last few days, I'm hoping that this issue will resolve itself in the next few days when a new version gets released. I believe the problem comes down to the way that vagrant sandboxes the libraries and binaries that it uses, while this plugin happens to shell out to the `VBoxManage` command directly - this seems to be the part that this plugin, and other libraries have implemented that causes the error that you see here.

I'll keep an eye on the vagrant releases, and upgrade as soon as I can - if this fixes the issue, I'll let you know. If it doesn't, I'll need to delve into vagrant again to see if there's a way I can get the output of `VBoxManage list vms` directly with the VirtualBox adapter - there wasn't when I originally wrote this plugin.

**Comment by joemaller** [comment]
Similar problem, I have some ruby code at the top of my vagrantfile [1] which sets up some variables, the `dyld: Symbol not found: _iconv` error 1.3.3 broke it. Works fine in 1.3.1 and 1.3.2.

Complete error:

```
dyld: Symbol not found: _iconv
  Referenced from: /usr/lib/libcups.2.dylib
  Expected in: /Applications/Vagrant/bin/../embedded/lib/libiconv.dylib
 in /usr/lib/libcups.2.dylib
```

1: http://stackoverflow.com/a/17729961/503463

Edit: Sorry, linked here and didn't notice this issue wasn't in Vagrant's repo...

**Comment by benregn** [comment]
Vagrant 1.3.4 seems to have fixed it.

**Comment by erunion** [comment]
Yep, can confirm. Thanks for looking into it, @joshmcarthur!
